### ISSUE TITLE
[Error: Key format must be specified]

### ISSUE THREAD

**Issue by danielchindea** [robi-richter/mobilpay-node#1]
Hi Robert,

Your mobilepay module is awesome, I need it and would gladly throw some beer to your place.
I face an error I cannot solve by myself:
[Error: Key format must be specified]
It comes from prepareRedirectData - > NodeRSA.importKey.

MobilPay public certificate is in 'cer' format.

What can I do, please please?

Thanks a million.

Daniel

**Comment by danielchindea** [comment]
Solved! I converted MobilPay public key and worked instantly. Thanks again for your work on the module.

**Comment by robi-richter** [comment]
@danielchindea yeah, I forgot to mention that :) I'll add that in the README file and maybe support multiple key formats

**Comment by danielchindea** [comment]
That would be a great idea.
I converted the cer to pem with
openssl x509 -inform pem -in PUBLIC_CERTIFICATE.cer -pubkey -noout > certificate_publickey.pem
